# Generated by Django 3.2.18 on 2023-05-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_comment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
